### PR TITLE
Modifications

### PR DESCRIPTION
**Pull request by wmbutler**
Here is the correct pull request. Sorry, I made some readme changes on my version that would have been wrong on yours.

### CODE REVIEW

**Comment by whitef0x0** [comment]
See my comment on the previous PR

**Comment by wmbutler** [comment]
I saw your comment after this. So, maybe a flag called `--keep`?

**Comment by whitef0x0** [comment]
@wmbutler might be better to add an options object when you require the library.

**Comment by wmbutler** [comment]
I'm not sure I follow.

**Comment by whitef0x0** [comment]
See this https://github.com/mattdesl/module-best-practices#api-best-practices

**Comment by whitef0x0** [comment]
@wmbutler I just added an option and added tests in this new PR https://github.com/johntayl/pdffiller/pull/54 based off your code.

**Comment by wmbutler** [comment]
Closing this in response to @whitef0x0 pull request.

**Pull request closed without merging**
