### PR TITLE
Support utf8 in fdf generation

### PR DESCRIPTION
**Pull request by JaakkoL**
I ran into a problem with fdf library used by this lib not supporting utf8. So I fixed the tests and switched it to [utf8-fdf-generator](https://www.npmjs.com/package/utf8-fdf-generator). Also added mocha and should to dev dependencies in the packages.

### CODE REVIEW

**Comment by Taakn** [comment]
I tested this and it works @johntayl. Thanks @JaakkoL

**Comment by Taakn** [comment]
@JaakkoL @johntayl actually I am seeing an error. Just a warning on dev, but an error in prod:
```
Error: Cannot find module '../build/Debug/iconv.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/pdffiller/node_modules/utf8-fdf-generator/node_modules/iconv/lib/iconv.js:29:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by Taakn** [comment]
Neverming it's working fine. After going to production I have to remove the folder `/bundle/bundle/programs/server/npm/node_modules/pdffiller/node_modules/utf8-fdf-generator/node_modules/iconv` then from within `/bundle/bundle/programs/server/npm/node_modules/pdffiller/node_modules/utf8-fdf-generator/node_modules/` do a `npm install iconv`.

Thanks for the great module

**Comment by JaakkoL** [comment]
@Taakn 👍

**Comment by whitef0x0** [comment]
@johntayl Can you close this issue?

**Pull request merged**
