### PR TITLE
Support PDF flattening as an option (re: Issue #31)

### PR DESCRIPTION
**Pull request by kevitan**
as in Issue #31

`fillForm()` takes an extra boolean argument, specifying
whether or not the resulting PDf should be read-only or remain
still-fillable for the remaining fields.

### CODE REVIEW

**Comment by whitef0x0** [comment]
You should add an example to the README as well

**Comment by kevitan** [comment]
done.

**Comment by whitef0x0** [comment]
You should probably add a test case if possible.

**Comment by kevitan** [comment]
Is the predicting one insufficient? It doesn't change the output in any testable way, does it?

**Comment by kevitan** [comment]
I've added unit tests and separated out a version that has an option for flatten. the original one curries into the new version.

**Comment by bluesockets** [comment]
+1

**Comment by whitef0x0** [comment]
@johntayl

**Pull request merged**
