### PR TITLE
Refactor GenFDFTempl and Clearer names for fdfs

### PR DESCRIPTION
**Pull request by somombo**
- Refactor generateFDFTemplate to convert 'true/false' to 'yes/off'
- Add "temporary" suffix to temporary fdf files to alert user that they can freely delete those files

### CODE REVIEW

**Comment by whitef0x0** [comment]
@Makombo I'm not entirely sure if yes/off is clearer than true/false.

**Comment by Makombo** [comment]
I don't believe this is about clarity. Simply that Acrobat's default values for checked/unchecked boxes is "yes/Off". I presume this was precisely why the `convFieldJson2FDF` function converts `true`/`false` to "yes/Off".

While `convFieldJson2FDF` and `generateFDFTemplate` are not exactly identical, I hope we can agree that they equivalent in the sense that they are returning the exact same type of object (refer to test cases). So if one of those two functions (`convFieldJson2FDF`) is  converting `true`/`false `to "yes/Off" why isn't the other?

**Comment by whitef0x0** [comment]
@somombo can you update your PR.

@johntayl can you have a look at this?

**Comment by somombo** [comment]
should be good now.. I still think the temporary files should still explicitly have at least "temp" as part of their name

**Comment by somombo** [comment]
thanks for incorporating the changes @johntayl

**Comment by johntayl** [comment]
No problem!

**Pull request merged**
